name: tax_tds
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  image_path: "assets/icon/icon.png"
  # image_path_android: "assets/icon/icon.png"
  # image_path_ios: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  # min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png



